# Files
executable = scriptcondor_performances_nano.sh
output = /afs/cern.ch/work/p/pdas/L1TrigDPG/nanoaod/CMSSW_13_1_0_pre4/src/MacrosNtuples/l1macros/condorsubmission/OUTPUTDIR/log/scriptcondor_$(ProcID).out
error = /afs/cern.ch/work/p/pdas/L1TrigDPG/nanoaod/CMSSW_13_1_0_pre4/src/MacrosNtuples/l1macros/condorsubmission/OUTPUTDIR/log/scriptcondor_$(ProcID).err
log = /afs/cern.ch/work/p/pdas/L1TrigDPG/nanoaod/CMSSW_13_1_0_pre4/src/MacrosNtuples/l1macros/condorsubmission/OUTPUTDIR/log/scriptcondor_$(ProcID).log

#transfer_input_files = $(filename)
arguments            = FILENAMES /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/pdas/NANOAOD/out/output_$(ClusterId)_$(ProcID).root CHANNEL GOLDENJSON

# File transfer behavior
#should_transfer_files = no
#when_to_transfer_output = ON_EXIT

# Resource requests
#request_cpus   = 4
#request_memory = 100MB
#request_disk   = 100MB
+JobFlavour = longlunch
getenv = True

# Optional resource requests
#+xcount = 4            # Request 4 cores
#+maxMemory = 4000      # Request 4GB of RAM
#+maxWallTime = 120     # Request 2 hrs of wall clock time
#+remote_queue = "osg"  # Request the OSG queue

# Run job
#queue filename matching files FILENAMES
queue
